import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildPropostaPayload, mapResponseToState } from '../js/admin/propostas/proposta_api.js';
import { propostaState, setProposta, atualizarCampoProposta, atualizarItem,
    atualizarPagamento, getPropostaPayload, getEditorProposta, resetPropostaState } from '../js/admin/propostas/proposta_state.js';

const response = JSON.parse(fs.readFileSync(new URL('./fixtures/proposta.json', import.meta.url)));
const original = structuredClone(response);
const mapped = mapResponseToState(response);
assert.equal(mapped.orcamento.nome_cliente, 'Cliente Teste');
assert.equal(mapped.orcamento.detalhes, 'Referencia do cliente');
setProposta(response);
assert.equal(propostaState.dirty, false);
assert.equal(getEditorProposta().data, '2026-09-11');
assert.equal(getEditorProposta().pagamento.valor_total, 150);
assert.equal(propostaState.proposta.pagamento, undefined);
const allowed = ['condicoes', 'descricao', 'itens', 'objeto', 'pagamentos', 'produtor_id'];
assert.deepEqual(Object.keys(getPropostaPayload()).sort(), allowed);
assert.deepEqual(buildPropostaPayload({ descricao: 'Patch', status: 'aceita' }), { descricao: 'Patch' });
atualizarCampoProposta('numero', 'forged');
atualizarCampoProposta('status', 'aceita');
atualizarCampoProposta('cliente_snapshot', {});
assert.equal(propostaState.dirty, false);
assert.equal(propostaState.proposta.numero, response.numero);
atualizarItem(0, 'subtotal', 99999);
assert.equal(propostaState.dirty, false);
atualizarItem(0, 'valor_unitario', 175);
assert.equal(propostaState.dirty, true);
assert.equal(getEditorProposta().pagamento.valor_total, 175);
assert.deepEqual(propostaState.proposta.totais, response.totais);
atualizarCampoProposta('produtor_id', '3');
assert.equal(getPropostaPayload().produtor_id, 3);
atualizarPagamento('entrada', 50);
assert.equal(getEditorProposta().pagamento.restante, 125);
atualizarPagamento('pagamento_parcial_2_url', 'https://example.com/final');
assert.equal(getPropostaPayload().pagamentos[2].habilitado, false);
atualizarPagamento('parcial_2_disponivel', true);
assert.equal(getPropostaPayload().pagamentos[2].habilitado, true);
atualizarPagamento('parcial_2_disponivel', false);
assert.equal(getPropostaPayload().pagamentos[2].habilitado, false);
propostaState.proposta.itens[0].subtotal = 99999;
propostaState.proposta.itens[0].id = 'local-only';
assert.equal(getPropostaPayload().itens[0].subtotal, undefined);
assert.equal(getPropostaPayload().itens[0].id, undefined);
assert.equal(getPropostaPayload().totais, undefined);
assert.equal(getPropostaPayload().pagamento, undefined);
assert.deepEqual(response, original);
const payload = getPropostaPayload();
setProposta(response);
assert.equal(propostaState.dirty, false);
assert.equal(propostaState.ui.locais.entrada, 0);
const extended = structuredClone(response);
extended.pagamentos.push({ tipo: 'parcial_3', titulo: 'Parcial 3', url: '', habilitado: false });
setProposta(extended);
assert.equal(getPropostaPayload().pagamentos.length, 4);
resetPropostaState();
assert.equal(getPropostaPayload(), null);
if (process.argv.includes('--json')) process.stdout.write(JSON.stringify(payload));
else console.log('PASS: response/state/payload, readonly, derived values, payments, dirty and isolation.');
