"""add etapas producao

Revision ID: 4b648eadd3e1
Revises: 5bf1dcfd7e41
Create Date: 2026-07-04 10:22:50.779235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b648eadd3e1'
down_revision: Union[str, Sequence[str], None] = '5bf1dcfd7e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producoes', sa.Column('etapas', sa.Text(), server_default="[]", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producoes', 'etapas')
    # ### end Alembic commands ###
