"""fix observacoes nullable

Revision ID: 5bf1dcfd7e41
Revises: b72cf77157b8
Create Date: 2026-07-03 10:37:21.730852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5bf1dcfd7e41"
down_revision: Union[str, Sequence[str], None] = "b72cf77157b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE orcamentos
        SET observacoes = ''
        WHERE observacoes IS NULL
        """)

    op.alter_column(
        "orcamentos", "observacoes", existing_type=sa.TEXT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orcamentos", "observacoes", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
