"""remove descricao_servico

Revision ID: 9d04ea8cadf5
Revises: b59e3f99f562
Create Date: 2026-06-28 10:48:32.593114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d04ea8cadf5'
down_revision: Union[str, Sequence[str], None] = 'b59e3f99f562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'descricao_servico')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('descricao_servico', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
