"""add estrutura_servico

Revision ID: b59e3f99f562
Revises: 
Create Date: 2026-06-28 08:53:59.748014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59e3f99f562'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "servicos",
        sa.Column(
            "estrutura_servico",
            sa.Text(),
            nullable=False,
            server_default='{"intro":"","sections":[],"benefits":[]}'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'estrutura_servico')
    # ### end Alembic commands ###
