"""add crm fields to orcamentos

Revision ID: b72cf77157b8
Revises: 9d04ea8cadf5
Create Date: 2026-07-03 08:31:08.106696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72cf77157b8'
down_revision: Union[str, Sequence[str], None] = '9d04ea8cadf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orcamentos",
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=True
        )
    )


    op.execute(
        """
        UPDATE orcamentos
        SET status = 'novo'
        WHERE status IS NULL
        """
    )


    op.alter_column(
        "orcamentos",
        "status",
        nullable=False
    )
    op.add_column('orcamentos', sa.Column('produtor_id', sa.Integer(), nullable=True))
    op.add_column(
    "orcamentos",
        sa.Column(
            "observacoes",
            sa.Text(),
            nullable=True
        )
    )

    op.execute(
        """
        UPDATE orcamentos
        SET observacoes = ''
        WHERE observacoes IS NULL
        """
    )

    op.alter_column(
        "orcamentos",
        "observacoes",
        nullable=False
    )
    op.add_column('orcamentos', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'orcamentos', 'usuarios', ['produtor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orcamentos', type_='foreignkey')
    op.drop_column('orcamentos', 'updated_at')
    op.drop_column('orcamentos', 'observacoes')
    op.drop_column('orcamentos', 'produtor_id')
    op.drop_column('orcamentos', 'status')
    # ### end Alembic commands ###
