"""add proposta fields to orcamentos

Revision ID: d1bdcc7920ab
Revises: f1f1b1ebdc8a
Create Date: 2026-07-09 07:57:38.388836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bdcc7920ab'
down_revision: Union[str, Sequence[str], None] = 'f1f1b1ebdc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('proposta_codigo', sa.String(length=30), nullable=True))
    op.add_column('orcamentos', sa.Column('proposta_pdf', sa.String(length=500), nullable=True))
    op.add_column('orcamentos', sa.Column('proposta_enviada', sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column('orcamentos', sa.Column('proposta_enviada_em', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orcamentos', 'status', existing_type=sa.VARCHAR(length=20), type_=sa.String(length=30), existing_nullable=False)
    op.execute(
        """
        UPDATE orcamentos
        SET status = 'arquivado'
        WHERE status = 'recusado'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orcamentos', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('orcamentos', 'proposta_enviada_em')
    op.drop_column('orcamentos', 'proposta_enviada')
    op.drop_column('orcamentos', 'proposta_pdf')
    op.drop_column('orcamentos', 'proposta_codigo')
    # ### end Alembic commands ###
