"""add prazo producao

Revision ID: f1f1b1ebdc8a
Revises: 4b648eadd3e1
Create Date: 2026-07-04 10:41:57.568192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f1f1b1ebdc8a"
down_revision: Union[str, Sequence[str], None] = "4b648eadd3e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "producoes",
        sa.Column("prazo_entrega", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("producoes", "prazo_entrega")
    # ### end Alembic commands ###
